---
#

- name: download filebeat
  template:
    src: filebeat-yum.repo.j2
    dest: "/etc/yum.repos.d/filebeat.repo"

- name: import elastic key
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: install filebeat
  yum: name=filebeat state=present
