---
# tasks file for elastic-filebeat
- include: install-filebeat.yml
  become: true
  become_user: root
  tags:
    - install

- include: configure-filebeat.yml
  become: true
  become_user: root
  tags:
    - configure
